x-common:
    database: &db-environment
        # Do not remove the "&db-password" from the end of the line below, it is important
        # for Panel functionality.
        MYSQL_PASSWORD: &db-password ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    panel: &panel-environment
        APP_URL: "https://panel.ynoacamino.site"
        APP_TIMEZONE: "UTC"
        APP_SERVICE_AUTHOR: "ynoacamino@gmail.com"
        VIRTUAL_HOST: "panel.ynoacamino.site,dashboard.enderhost.online"
        LETSENCRYPT_HOST: "panel.ynoacamino.site,dashboard.enderhost.online"
        LETSENCRYPT_EMAIL: "ynoacamino@gmail.com"
        VIRTUAL_PORT: "80"
    mail: &mail-environment
        MAIL_FROM: ${MAIL_FROM}
        MAIL_DRIVER: ${MAIL_DRIVER}
        MAIL_HOST: ${MAIL_HOST}
        MAIL_PORT: ${MAIL_PORT}
        MAIL_USERNAME: ${MAIL_USERNAME}
        MAIL_PASSWORD: ${MAIL_PASSWORD}
        MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#

services:
    database:
        image: library/mysql:8.0
        restart: always
        networks:
            - local
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "./database:/var/lib/mysql"
        environment:
            <<: *db-environment
            MYSQL_DATABASE: "panel"
            MYSQL_USER: "pterodactyl"

    cache:
        image: redis:alpine
        restart: always
        networks:
            - local

    panel:
        image: ghcr.io/pterodactyl/panel:v1.11.10
        restart: always
        networks:
            - web-services
            - local
        links:
            - database
            - cache
        volumes:
            - "./panel/var/:/app/var/"
            - "./panel/logs/:/app/storage/logs"
            - "./panel/nginx/:/etc/nginx/conf.d/"
        environment:
            <<: [*panel-environment, *mail-environment]
            DB_PASSWORD: *db-password
            APP_ENV: "production"
            APP_ENVIRONMENT_ONLY: "false"
            CACHE_DRIVER: "redis"
            SESSION_DRIVER: "redis"
            QUEUE_DRIVER: "redis"
            REDIS_HOST: "cache"
            DB_HOST: "database"
            TRUSTED_PROXIES: "*"

networks:
    local:
        external: false
    web-services:
        external: true
