services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.nginx-proxy.docker-gen"

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=ynoacamino@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  up:
    build:
      context: ./ynoa-uploader-page/
    container_name: up
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - VIRTUAL_HOST=up.ynoacamino.site
      - LETSENCRYPT_HOST=up.ynoacamino.site
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_MAIL=ynoacamino@gmail.com
    depends_on:
      - nginx-proxy
      - docker-gen
      - acme-companion
    
  uploader:
    build:
      context: ./ynoa-uploader/
    container_name: uploader
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - VIRTUAL_HOST=uploader.ynoacamino.site
      - LETSENCRYPT_HOST=uploader.ynoacamino.site
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_MAIL=ynoacamino@gmail.com
    depends_on:
      - nginx-proxy
      - docker-gen
      - acme-companion

  portafolio:
    build:
      context: ./portafolio/
    container_name: portafolio
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - VIRTUAL_HOST=ynoacamino.site
      - LETSENCRYPT_HOST=ynoacamino.site
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_MAIL=ynoacamino@gmail.com
    depends_on:
      - nginx-proxy
      - docker-gen
      - acme-companion

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    healthcheck:
      disable: true
    ports:
      - 3200:3200
      - 3201:3201
    environment:
      - MINIO_ROOT_USER=ynoacamino
      - MINIO_ROOT_PASSWORD=11yenaro11
      - LETSENCRYPT_HOST=minio.ynoacamino.site,minio-admin.ynoacamino.site
      - 'VIRTUAL_HOST_MULTIPORTS={"minio.ynoacamino.site":{"/":{"port":"3200"}},"minio-admin.ynoacamino.site":{"/":{"port":"3201"}}}'
      - LETSENCRYPT_MAIL=ynoacamino@gmail.com
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - ./minio-data/:/data/
    depends_on:
      - nginx-proxy
      - docker-gen
      - acme-companion

  museum:
    image: ghcr.io/ente-io/server
    restart: unless-stopped
    container_name: museum
    healthcheck:
      disable: true
    depends_on:
      - postgres-museum
      - nginx-proxy
      - docker-gen
      - acme-companion
    environment:
      - ENTE_CREDENTIALS_FILE=/credentials.yaml
      - VIRTUAL_HOST=ente.ynoacamino.site
      - LETSENCRYPT_HOST=ente.ynoacamino.site
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_MAIL=ynoacamino@gmail.com
    volumes:
      - ./config-ente/museum.yaml:/museum.yaml:ro
      - ./config-ente/credentials.yaml:/credentials.yaml:ro

  postgres-museum:
    container_name: postgres-museum
    image: postgres:15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ente_db

  #nextcloud:
    #  image: nextcloud
    #container_name: nextcloud
    #restart: unless-stopped
    #volumes:
      #  - nextcloud:/var/www/html
    #environment:
      # - VIRTUAL_HOST=next.ynoacamino.site
      #- LETSENCRYPT_HOST=next.ynoacamino.site
      #- VIRTUAL_PORT=80
      #- LETSENCRYPT_MAIL=ynoacamino@gmail.com
    #network_mode: bridge
    #depends_on:
      #  - nginx-proxy
      #- docker-gen
      #- acme-companion
  #vscode:
    #  build:
    #  context: ./vscode-docker/
    #container_name: vscode
    #restart: unless-stopped
    #healthcheck:
    #  disable: true
    #environment:
    # - VIRTUAL_HOST=code.ynoacamino.site
      #  - LETSENCRYPT_HOST=code.ynoacamino.site
      #- LETSENCRYPT_MAIL=ynoacamino@gmail.com
      #- VIRTUAL_PORT=8585
    #network_mode: bridge
    #depends_on:
      #  - nginx-proxy
      #- docker-gen
      #- acme-companion

volumes:
  vhost:
  conf:
  html:
  certs:
  acme:

