services:
  code:
    image: nginx:alpine
    container_name: code
    restart: unless-stopped
    healthcheck:
      disable: true
    #environment:
      #- VIRTUAL_HOST=code.ynoacamino.site
      #- LETSENCRYPT_HOST=uploader.ynoacamino.site
      #- VIRTUAL_PORT=3000
      #- LETSENCRYPT_MAIL=ynoacamino@gmail.com
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro  
    networks:
      - web-services

networks:
  web-services:
    external: true
