services:
  stt:
    image: ynoacamino/speek-to-text-server:v0.4
    container_name: stt
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - VIRTUAL_HOST=stt.ynoacamino.site
      - LETSENCRYPT_HOST=stt.ynoacamino.site
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_MAIL=ynoacamino@gmail.com
    networks:
      - web-services

networks:
  web-services:
    external: true
