services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    networks:
      - web-services

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.nginx-proxy.docker-gen"
    networks:
      - web-services

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=ynoacamino@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web-services

  #minio:
    #  image: minio/minio
    #  container_name: minio
    #  restart: unless-stopped
    #  healthcheck:
    #  disable: true
    #  ports:
      #  - 3200:3200
      #  - 3201:3201
    #  environment:
      #  - MINIO_ROOT_USER=ynoacamino
      #  - MINIO_ROOT_PASSWORD=11yenaro11
      #  - LETSENCRYPT_HOST=minio.ynoacamino.site,minio-admin.ynoacamino.site
      #  - 'VIRTUAL_HOST_MULTIPORTS={"minio.ynoacamino.site":{"/":{"port":"3200"}},"minio-admin.ynoacamino.site":{"/":{"port":"3201"}}}'
      #  - LETSENCRYPT_MAIL=ynoacamino@gmail.com
    #  command: server /data --address ":3200" --console-address ":3201"
    #  volumes:
      #  - ./minio-data/:/data/
    #  depends_on:
      #  - nginx-proxy
      #  - docker-gen
      #  - acme-companion

volumes:
  vhost:
  conf:
  html:
  certs:
  acme:

networks:
  web-services:
    external: true

