services:
  acm-panel:
    image: ynoacamino/student-chapter-acm-page-panel:panel-v0.6
    restart: unless-stopped
    container_name: acm-panel
    healthcheck:
      disable: true
    environment:
      - VIRTUAL_HOST=acm-panel.ynoacamino.site
      - LETSENCRYPT_HOST=acm-panel.ynoacamino.site
      - VIRTUAL_PORT=8090
      - LETSENCRYPT_MAIL=ynoacamino@gmail.com
    volumes:
      - ./data/:/pb/pb_data/
    env_file: .env
    networks:
      - web-services

networks:
  web-services:
    external: true
