services:
  uploader:
    image: ynoacamino/ynoa-uploader:latest
    container_name: uploader
    restart: unless-stopped
    healthcheck:
      disable: true
    env_file: .env
    environment:
      - VIRTUAL_HOST=uploader.ynoacamino.site
      - LETSENCRYPT_HOST=uploader.ynoacamino.site
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_MAIL=ynoacamino@gmail.com
    networks:
      - web-services

networks:
  web-services:
    external: true
