services:
  uploader:
    build:
      context: ./ynoa-uploader/
    container_name: uploader
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - VIRTUAL_HOST=uploader.ynoacamino.site
      - LETSENCRYPT_HOST=uploader.ynoacamino.site
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_MAIL=ynoacamino@gmail.com
    networks:
      - web-services

networks:
  web-services:
    external: true
