services:
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - MINIO_ROOT_USER=ynoacamino
      - MINIO_ROOT_PASSWORD=11yenaro11
      - LETSENCRYPT_HOST=minio.ynoacamino.site,minio-admin.ynoacamino.site
      - 'VIRTUAL_HOST_MULTIPORTS={"minio.ynoacamino.site":{"/":{"port":"3200"}},"minio-admin.ynoacamino.site":{"/":{"port":"3201"}}}'
      - LETSENCRYPT_MAIL=ynoacamino@gmail.com
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - ./minio-data/:/data/

networks:
  web-services:
    external: true
