services:
  secrets-backend:
    image: ynoacamino/ynoacamino-secrets-backend
    restart: unless-stopped
    container_name: secrets-backend
    healthcheck:
      disable: true
    environment:
      - VIRTUAL_HOST=secrets-admin.ynoacamino.site
      - LETSENCRYPT_HOST=secrets-admin.ynoacamino.site
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_MAIL=ynoacamino@gmail.com
    volumes:
      - ./pb_data/:/pb/pb_data/
    env_file: .env
    networks:
      - web-services

  secrets-frontend:
    image: ynoacamino/ynoacamino-secrets-frontend:v0.4
    restart: unless-stopped
    container_name: secrets-frontend
    healthcheck:
      disable: true
    environment:
      - VIRTUAL_HOST=secrets.ynoacamino.site
      - LETSENCRYPT_HOST=secrets.ynoacamino.site
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_MAIL=ynoacamino@gmail.com
    env_file: .env
    networks:
      - web-services

networks:
  web-services:
    external: true
